---
sudo: false
dist: precise
language: java
matrix:
  include:
    - jdk: oraclejdk7
      dist: precise
    - jdk: oraclejdk8
      dist: trusty
    - jdk: oraclejdk9
      dist: trusty
after_success:
  - bash <(curl -s https://codecov.io/bash)
