name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  compile:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 17, 23]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Compile with Maven
        run: mvn -e --batch-mode compile -T 1C

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [21]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Test with Maven
        run: mvn -e --batch-mode verify -T 1C
      - name: Run Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
